### ISSUE TITLE
add 1inch fusion support

### ISSUE THREAD

**Issue by a6-dou** [trustwallet/wizard-sdk#9]
ensure you include enough in-code documentation, references, and +90% test coverage

**Comment by legendarykamal** [comment]
Hello @a6-dou what would be the best way to connect with you inorder to understand more about this issue ? thanks .

**Comment by a6-dou** [comment]
Hey @legendarykamal , i am reachable via [discord](https://discord.gg/qsg4cJVZGY)

**Comment by Maliksb11** [comment]
ok
